highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


url: http://tapasweni-pathak.github.io/
baseurl: http://tapasweni-pathak.github.io/
title: Piyush Singhai
author: Piyush Singhai
description: Homepage of Piyush Singhai.
avatar: profile.png
email: singhai.piyush@gmail.com
github: piyushiitg # username
twitter: piyush_iitg
linkedin: Piyush Singhai


# needed for travis-ci build
exclude: [vendor]
